;;; help-find-org-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from help-find-org-mode.el

(defvar help-find-org-mode nil "\
Non-nil if Help-Find-Org mode is enabled.
See the `help-find-org-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `help-find-org-mode'.")
(custom-autoload 'help-find-org-mode "help-find-org-mode" nil)
(autoload 'help-find-org-mode "help-find-org-mode" "\
Advise help functions that find source files to find org babel

source blocks instead of tangled source.

This is a global minor mode.  If called interactively, toggle the
`Help-Find-Org mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='help-find-org-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "help-find-org-mode" '("help-find-org-"))

;;; End of scraped data

(provide 'help-find-org-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; help-find-org-mode-autoloads.el ends here
