;;; flymake-aspell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-aspell.el

(autoload 'flymake-aspell-setup "flymake-aspell" "\
Enable the spell checker for the current buffer." t)
(register-definition-prefixes "flymake-aspell" '("flymake-aspell-"))

;;; End of scraped data

(provide 'flymake-aspell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-aspell-autoloads.el ends here
