;;; gpt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gpt-api.el

(register-definition-prefixes "gpt-api" '("gpt-"))


;;; Generated autoloads from gpt-core.el

(register-definition-prefixes "gpt-core" '("gpt-"))


;;; Generated autoloads from gpt-mode.el

(register-definition-prefixes "gpt-mode" '("gpt-"))


;;; Generated autoloads from gpt-ui.el

(autoload 'gpt-chat-multi-models "gpt-ui" "\
Run GPT command against multiple models in parallel.
CONTEXT-MODE can be one of:
- \\='all-buffers: Use all visible buffers as context
- \\='current-buffer: Use current buffer as context
- nil or \\='none: Use no buffer context

By default, uses `gpt-multi-models-default' without prompting.
With a prefix argument (C-u), prompts to choose models interactively.

(fn &optional CONTEXT-MODE PROMPT-FOR-MODELS)" t)
(autoload 'gpt-edit-current-buffer "gpt-ui" "\
Rewrite the current buffer via GPT and apply changes after review." t)
(autoload 'gpt-chat "gpt-ui" "\
Run user-provided GPT command with configurable context and print output stream.
CONTEXT-MODE can be:
- ='all-buffers: Use all visible buffers as context
- ='current-buffer: Use current buffer as context
- nil or ='none: Use no buffer context
In all cases, if there is an active region, it will be included.

(fn &optional CONTEXT-MODE)" t)
(autoload 'gpt-chat-all-buffers "gpt-ui" "\
Run GPT command with all visible buffers as context." t)
(autoload 'gpt-chat-current-buffer "gpt-ui" "\
Run GPT command with current buffer as context." t)
(autoload 'gpt-chat-no-context "gpt-ui" "\
Run GPT command with no buffer context." t)
(autoload 'gpt-toggle-thinking "gpt-ui" "\
Toggle extended thinking mode for Anthropic models (enabled by default)." t)
(autoload 'gpt-toggle-interleaved-thinking "gpt-ui" "\
Toggle interleaved thinking mode for Anthropic models (enabled by default)." t)
(autoload 'gpt-toggle-web-search "gpt-ui" "\
Toggle web search for Anthropic models." t)
(autoload 'gpt-thinking-status "gpt-ui" "\
Display current thinking mode settings." t)
(register-definition-prefixes "gpt-ui" '("gpt-"))

;;; End of scraped data

(provide 'gpt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gpt-autoloads.el ends here
